{
 "title": "Spring Boot Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Query" },
   { "name": "Filters" },
   {
    "name": "instance",
    "label": "Application instance",
    "query": {
     "query": "label_values({application=\"$app_name\"},instance)"
    }
   },
   {
    "name": "env_instance",
    "query": {
     "query": "label_values({instance=\"$instance\"},instance_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fast Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  (\r\n    sum by(uri) (rate(http_server_requests_seconds_sum{application=\"$app_name\", instance=\"$instance\"}[$__rate_interval]))\r\n    /\r\n    sum by(uri) (rate(http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\"}[$__rate_interval]))\r\n  ) < 3\r\n)\r\n",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Long Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((\r\n  sum by(uri) (rate(http_server_requests_seconds_sum{application=\"$app_name\", instance=\"$instance\",}[$__rate_interval]))\r\n  / \r\n  sum by(uri) (rate(http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\",}[$__rate_interval]))\r\n)) >= 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by(uri) (\r\n    increase(http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\", uri!=\"/actuator/prometheus\", uri!=\"UNKNOWN\", uri!=\"/api/actuator/prometheus\"}[24h])\r\n  )\r\n) > 0",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\", uri!=\"/actuator/prometheus\", uri!=\"/api/actuator/prometheus\", uri!=\"UNKNOWN\"}[24h]))\r\n"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\", outcome=\"SERVER_ERROR\"}[24h]))\r\n"
    }
   ]
  },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"$app_name\", env=\"$env_instance\"}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (rate({service=\"$app_name\",  env=\"$env_instance\"} | pattern `<date> <time> <_>=<trace_id> <_>=<span_id> <_>=<trace_flags> <type> <_> --- <msg>` |= \"$log_keyword\" [1m]))\n"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\", uri!=\"/api/actuator/prometheus\", uri!=\"UNKNOWN\"}[1m]))"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/api/actuator/prometheus\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", instance=\"$instance\", status=~\"5.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", instance=\"$instance\", uri!=\"/api/actuator/prometheus\", uri!=\"UNKNOWN\"}[30m])) by (uri, le))\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", instance=\"$instance\", uri!=\"/api/actuator/prometheus\", uri!=\"UNKNOWN\"}[30m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}