spring:
  application:
    name: email-notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_APP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  threads:
    virtual:
      enabled: true

app:
  messaging:
    rabbit:
      exchange: event.notifications
      routing-key: event.created
      queue: event.notifications.new-events
  mail:
    from: ${MAIL_FROM:noreply@example.com}
  website-url: http://192.168.0.119:3000
  metrics:
    username: ${PROMETHEUS_USERNAME}
    password: ${PROMETHEUS_PASSWORD}
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
      base-path: /api/actuator
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}