app:
  static-content:
    path: ${STATIC_CONTENT_PATH}
  security:
    jwt:
      access-token:
        secret: ybPsdl@zizYpYQ#-|~FP1M|?x_w;s8V3Bsl0CX+7nHD1]-%q;e<[,B7S((op&s+M
        expiration: 900000 # 15 minutes
      refresh-token:
        secret: agwj?4)U1i_6[gg16_l28=>^`J6s4Wtc`T/ye6R+]2uMqY{Y]<q'uzQRmkuY@FeX
        expiration: 2592000000 # 30 days
      issuer: event space
  account:
    deletion-confirmation-phrase: "удалить мой аккаунт"

spring:
  application:
    name: event-space-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event_space_db
    username: postgres
    password: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true