--liquibase formatted sql

--changeset alex:1
CREATE TABLE event
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(128) NOT NULL ,
    tags text[],
    event_date date,
    start_time time,
    end_time time CHECK ( end_time > start_time ),
    space_id int REFERENCES space(id) NOT NULL ,
    description text,
    image_url text
)