--liquibase formatted sql

--changeset alex:1
CREATE TABLE event_step
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    event_id int REFERENCES event(id) NOT NULL ,
    name varchar(64) NOT NULL ,
    start_time time NOT NULL ,
    end_time time NOT NULL ,
    description varchar(128),
    UNIQUE (event_id, name)
)