--liquibase formatted sql

--changeset alex:1
ALTER TABLE event_user RENAME TO event_user_old;

--changeset alex:2
CREATE TABLE event_user
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL REFERENCES event ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users ON DELETE CASCADE,
    attended boolean NOT NULL DEFAULT false,
    UNIQUE (event_id, user_id)
);

--changeset alex:3
INSERT INTO event_user (event_id, user_id)
SELECT event_id, user_id FROM event_user_old;

--changeset alex:4
DROP TABLE event_user_old;