worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name localhost;

        location /media/ {
            alias /usr/share/nginx/html/media/;

            expires 30d;
            add_header Cache-Control "public";

            autoindex on;
        }

        location / {
            return 404;
        }
    }
}