--liquibase formatted sql

--changeset alex:1
CREATE TABLE users
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    first_name varchar(64) NOT NULL ,
    last_name varchar(64) NOT NULL ,
    email varchar(320) NOT NULL UNIQUE ,
    role varchar(32),
    course smallint CHECK ( course BETWEEN 1 AND 4) ,
    description varchar(256),
    phone varchar(16) UNIQUE ,
    avatar_url text,
    tg_username varchar(32),
    vk_url text,
    github_url text,
    is_active boolean DEFAULT true,
    register_date date,
    faculty_id int REFERENCES faculty(id) NOT NULL
)