--liquibase formatted sql

--changeset alex:1
CREATE TABLE faculty
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(128) NOT NULL UNIQUE ,
    building_id int REFERENCES building(id) NOT NULL
);