--liquibase formatted sql

--changeset alex:1
CREATE TABLE space
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(64) NOT NULL ,
    building_id int REFERENCES building(id) NOT NULL ,
    UNIQUE (name, building_id)
);