--liquibase formatted sql

--changeset alex:1
CREATE TABLE event_review
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id) NOT NULL ,
    event_id int REFERENCES event(id) NOT NULL ,
    title varchar(128) NOT NULL ,
    content varchar(1000) NOT NULL ,
    rating smallint CHECK ( rating BETWEEN 1 AND 5) NOT NULL ,
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
)