--liquibase formatted sql

--changeset alex:1
CREATE TABLE complaint
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    author_id int REFERENCES users(id) NOT NULL,
    target varchar(256) NOT NULL,
    complaint_type_id int REFERENCES complaint_type(id) NOT NULL ,
    complaint_date date NOT NULL ,
    status varchar(64) NOT NULL
)