--liquibase formatted sql

--changeset alex:1
CREATE TABLE helpful_mark
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id) NOT NULL ,
    review_id int REFERENCES event_review(id) NOT NULL ,
    UNIQUE (user_id, review_id),
    created_at timestamp with time zone DEFAULT NOW()
)